dataset_path: data/example_dataset

compression:
  required: True
  values: # crf values
    - 25
    - 30
    - 40
    - 50

scaling:
  required: True
  values: # scale factors. not including 1.0
    - 0.8
    - 0.6
    - 0.4
    - 0.2