dataset_path: data/dataset_small

# Pre-processing
compression:
  required: False
  values: # crf values
    - 25
    - 30
    - 40
    - 50

scaling:
  required: False
  values: # scale factors. not including 1.0
    - 0.8
    - 0.6
    - 0.4
    - 0.2

# Extraction
extraction:
  required: True
  to_extract_dir: train
  extracted_path: data/extracted_small
  extractors:
    py-feat:
      - Pitch
      - Roll
      - Yaw
      - AU01
      - AU02
      - AU04
      - AU05
      - AU06
      - AU07
      - AU09
      - AU10
      - AU11
      - AU12
      - AU14
      - AU15
      - AU17
      - AU20
      - AU23
      - AU24
      - AU25
      - AU26
      - AU28
      - AU43

# Correlations
correlations:
  required: False
  correlations_path: data/correlations_small
  clip_configs:
    0:
      length: 20
      overlap: 10
    # 1:
    #   length: 15
    #   overlap: 10
    # 2:
    #   length: 10
    #   overlap: 5
    # 3:
    #   length: 5
    #   overlap: 2.5
    # 4:
    #   length: 3
    #   overlap: 1.5